/* groovylint-disable LineLength */
pipeline {
    agent any
                 
   environment { 
            HELLO_VERSION= '1.0.'
           }
        stages {
            stage('Initial Notification') {
                steps {
                    //put webhook for your notification channel
                    echo "Build ${env.JOB_NAME} branche ${env.BRANCH_NAME}  version HELLO_VERSION{env.BUILD_NUMBER}-${env.BRANCH_NAME}"
                    //sh 'export PATH="$PATH:/root/.dotnet/tools"'
                }
            } 
            stage('Restore') {
                steps {                    
                    sh 'dotnet restore HelloJenkins.sln'
                }
            }
            stage('Build') {
                steps {
                    sh 'dotnet build HelloJenkins.sln'
                }
            }
          
            stage('Test') {
                steps {
                    sh 'dotnet test  HelloJenkins.sln'
                    sh 'dotnet test  HelloJenkins.sln'
               }
            }
            stage('CleanDown') {
                steps {
                    sh "rm -rf nupkgs"
                }
            }
        }
    }
}
