version: '3.4'

services:
    
    jenkins:
        build:
            dockerfile: Jenkins/Dockerfile
            context: .
        env_file: 
            - env-file.md
        volumes:
            - 'd:\mousquetairejenkins_data:/bitnami/jenkins'
            - 'd:\mousquetairejenkins_conf:/var/jenkins_home'  
        ports: 
            - 8080:8080
            
       
           